version: '3'

services:
  api:
    build: .
    command: ./start_dev.sh
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db

  db:
    image: postgres
    ports:
      - "5432:5432"
